name: goproapp
description: "App for surveyor."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  wifi_iot: ^0.3.19+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/logoLogin.jpeg
  - assets/images/viewMediaHerey.jpg
  - assets/images/jalanTest.jpeg